apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  dnsNames:
  - {{ include "chart.fullname" . }}.{{ .Release.Namespace }}.svc
  - {{ include "chart.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ include "chart.fullname" . }}
  secretName: {{ include "chart.fullname" . }}-tls
---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  selfSigned: {}
